name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Run build.sh
        run: |
          bash build.sh

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          asset_path: pois.build/exe-file-name
          asset_name: exe-file-name
          release_id: ${{ github.event.release.id }}
